# Generated by Django 4.2.2 on 2023-07-28 19:27

from django.db import migrations, models
import testimonial.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default=testimonial.models.get_default_image, null=True, upload_to='testimonial_images/')),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
    ]
