# Generated by Django 4.2.2 on 2023-07-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issueID', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='blog/thumbnails/')),
                ('video', models.URLField(blank=True)),
                ('image1', models.ImageField(blank=True, upload_to='blog/images2/')),
                ('image2', models.ImageField(blank=True, upload_to='blog/images2/')),
                ('image3', models.ImageField(blank=True, upload_to='blog/images2/')),
                ('image4', models.ImageField(blank=True, upload_to='blog/images2/')),
                ('image5', models.ImageField(blank=True, upload_to='blog/images2/')),
                ('category', models.CharField(default='mobile', max_length=50)),
                ('client', models.CharField(blank=True, default='user', max_length=100)),
                ('project_issue', models.DateField()),
                ('project_finish', models.DateField()),
                ('repairing_cost', models.DecimalField(decimal_places=2, default='hidden', max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
