# Generated by Django 4.2.2 on 2023-07-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('subscriptionemail', models.EmailField(max_length=50)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
